### PR TITLE
Add Cask for this driver.

### PR DESCRIPTION
**Pull request by mengbo**
Now, This driver can be installed by homebrew-cask.

### CODE REVIEW

**Comment by mengbo** [comment]
You should change the `brew tap` command url to your repository url.

**Comment by briantopping** [comment]
Very cool! How about rebase this to a single commit?

**Comment by objque** [comment]
Any news? Could I install it from brew?

**Comment by adrianmihalko** [comment]
@mengbo can you please make a pull request for 1.5 version?

**Pull request merged**
