### PR TITLE
Update 1.4 (2017-01-11) files, direct from OEM website

### PR DESCRIPTION
**Pull request by BrettDikeman**
In troubleshooting problems with a printer, I found newer drivers on the vendor's site. They're properly signed, and do not cause a crash **on El Capitan**. I'm unable to test on Sierra.

- New pkg and zip files (please verify against vendor's site)
- Readme (I'm not attached to any of it; feel free to re-edit):
  - Updated for the new version
  - Tried rewording some no-longer-applicable sections
  - Added a link to Apple's docs on enabling/disabling System Integrity Protection
- Cask file:
  - checksum (please verify)
  - version
  - URL
  - changed the warning about the drivers being from an unknown source to one that says they're from the OEM's website.
- gitignore to ignore DS_Store files.

Feedback welcome!

### CODE REVIEW

**Comment by allenhuffman** [comment]
Is the 1.4 in this update just the package from the vendor's site?

**Comment by BrettDikeman** [comment]
Hi Allen,

I'm not 100% sure what you mean, but...the zip file is from the vendor's
site, and the pkg file is from said zip file.

**Comment by allenhuffman** [comment]
I originally found this site after not having luck with the official drivers. The drives I downloaded from this repository worked — what were those? If this repository is just taking their drivers and posting here, what is the point? Just trying to figure out what is what.

**Comment by BrettDikeman** [comment]
Allen,

The version that caused crashes has long since been removed from their site. They removed the buggy version in January of 2017 when they made a new version available.

 @adrianmihalko is the person to ask regarding their motivations in setting up the repo, or how they came by the version of the driver that in the current master branch - however, my suspicion is that it was distributed by the OEM in some capacity (say, emailed out to corporate customer, who then distributed to their users), just not via their website.

One "point" is that this repo is how Adrian is maintaining their Cask file. It also serves as a more reliable distribution method; many of these OEMs have website reliability issues, files get infected or corrupted, etc - and GitHub is very stable and reliable, there are checksums, etc. Another is that multiple versions of the drivers would be accessible from this repo, not just whatever version the OEM has on their site at a particular moment. One need only look at an older release or commit to get the version that works for their particular OS and device(s) if the most current one does not.

**Comment by waspinator** [comment]
the version in this repo crashes macOS High Sierra 10.13.3. This OEM version worked for me (http://www.wch.cn/download/CH341SER_MAC_ZIP.html).

also, @adrianmihalko can you enable issues for this repo?

**Review by adrianmihalko — APPROVED** [review]
Merged.

**Comment by cdaringe** [comment]
i am still seeing the following, per download on this site:

screen shot 2018-06-06 at 9 18 21 pm

this is counter to "not required" message in the README.  is this expected?

**Pull request merged**
